version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install requirements and run tests
          command: |
            virtualenv venv
            source venv/bin/activate
            pip3 install -r requirements/requirements-dev.txt
            export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
            python3 -m unittest
